name: example
description: A sample modular-api application.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  modular_api:
    path: ../
  # change to lastest version
  # service_client: ^lastest_version
  # service_client:
  #   path: ../../service_client
  service_client: ^0.1.0
  postgres: ^3.0.0
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  http: ^1.5.0
