
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.

module "dart-shelf-postgresql-app-service" {
  source                        = "github.com/GoogleCloudPlatform/terraform-google-cloud-run//modules/v2?ref=v0.21.4"
  project_id                    = "cacsi-451017"
  location                      = "us-central1"
  service_name                  = "cloud-run-api"
  containers                    = [{"container_image" = "gcr.io/cloudrun/dart-shelf-app", "container_name" = "dart-shelf-container", "env_secret_vars" = {"dart_shelf_postgresql_app_database_secret_SECRET" = module.dart-shelf-postgresql-app-database-secret.env_vars.SECRET}, "env_vars" = {"dart_shelf_postgresql_app_database_postgresql_CLOUD_SQL_DATABASE_CONNECTION_NAME" = module.dart-shelf-postgresql-app-database-postgresql.instance_connection_name, "dart_shelf_postgresql_app_database_postgresql_CLOUD_SQL_DATABASE_HOST" = module.dart-shelf-postgresql-app-database-postgresql.instance_first_ip_address, "dart_shelf_postgresql_app_database_postgresql_CLOUD_SQL_DATABASE_NAME" = module.dart-shelf-postgresql-app-database-postgresql.env_vars.CLOUD_SQL_DATABASE_NAME}}]
  gpu_zonal_redundancy_disabled = false
  service_account_project_roles = concat(["roles/cloudsql.instanceUser", "roles/cloudsql.client"], ["roles/secretmanager.secretAccessor"])
  members                       = ["allUsers"]
  vpc_access = {
    egress = "ALL_TRAFFIC"
    network_interfaces = {
      network    = "default"
      subnetwork = "default"
    }
  }
  cloud_run_deletion_protection = false
  enable_prometheus_sidecar     = true
  service_scaling = {
    min_instance_count = 0
  }
  template_scaling = {
    min_instance_count = 0
  }
  depends_on = [module.project-services-cacsi-451017, module.project-services-billing-project]
}
module "dart-shelf-postgresql-app-database-postgresql" {
  source                      = "github.com/terraform-google-modules/terraform-google-sql-db//modules/postgresql?ref=v26.2.2"
  project_id                  = "cacsi-451017"
  name                        = "postgresql-db"
  edition                     = "ENTERPRISE_PLUS"
  database_version            = "POSTGRES_16"
  availability_type           = "REGIONAL"
  deletion_protection         = false
  database_flags              = [{"name" = "cloudsql.iam_authentication", "value" = "on"}]
  data_cache_enabled          = true
  tier                        = "db-perf-optimized-N-8"
  deletion_protection_enabled = false
  disk_autoresize             = true
  backup_configuration = {
    enabled                        = true
    point_in_time_recovery_enabled = true
  }
  iam_users = [{
    email = module.dart-shelf-postgresql-app-service.service_account_id.email
    id    = module.dart-shelf-postgresql-app-service.service_account_id.id
    type  = "CLOUD_IAM_SERVICE_ACCOUNT"
  }]
  depends_on = [module.project-services-cacsi-451017, module.project-services-billing-project]
}
module "dart-shelf-postgresql-app-database-secret" {
  source      = "github.com/GoogleCloudPlatform/terraform-google-secret-manager//modules/simple-secret?ref=v0.9.0"
  project_id  = "cacsi-451017"
  name        = "db-credentials"
  secret_data = module.dart-shelf-postgresql-app-database-postgresql.generated_user_password
  depends_on  = [module.project-services-cacsi-451017, module.project-services-billing-project]
}
module "global-lb-frontend" {
  source                          = "github.com/terraform-google-modules/terraform-google-lb-http//modules/frontend?ref=v13.2.0"
  name                            = "miapp-lb-frontend"
  project_id                      = "cacsi-451017"
  url_map_input                   = module.global-lb-backend.backend_service_info
  ssl                             = true
  managed_ssl_certificate_domains = ["miapp.miempresa.com"]
  https_redirect                  = true
  depends_on                      = [module.project-services-cacsi-451017, module.project-services-billing-project]
}
module "global-lb-backend" {
  source     = "github.com/terraform-google-modules/terraform-google-lb-http//modules/backend?ref=v13.2.0"
  name       = "miapp-lb-backend"
  project_id = "cacsi-451017"
  serverless_neg_backends = [{
    region          = module.dart-shelf-postgresql-app-service.location
    service_name    = module.dart-shelf-postgresql-app-service.service_name
    service_version = ""
    type            = "cloud-run"
  }]
  host_path_mappings = [{"host" = "miapp.miempresa.com", "path" = "/api/*"}]
  depends_on         = [module.project-services-cacsi-451017, module.project-services-billing-project]
}
module "apphub" {
  source         = "github.com/GoogleCloudPlatform/terraform-google-apphub?ref=v0.3.0"
  project_id     = var.apphub_project_id
  location       = var.apphub_location
  service_uris   = concat([module.dart-shelf-postgresql-app-service.apphub_service_uri], [module.dart-shelf-postgresql-app-database-postgresql.apphub_service_uri], module.global-lb-frontend.apphub_service_uri, module.global-lb-backend.apphub_service_uri)
  application_id = var.apphub_application_id
}
module "project-services-cacsi-451017" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v17.1.0"
  project_id                  = "cacsi-451017"
  disable_services_on_destroy = false
  activate_apis               = []
}
module "project-services-billing-project" {
  source                      = "github.com/terraform-google-modules/terraform-google-project-factory//modules/project_services?ref=v17.1.0"
  project_id                  = "cacsi-451017"
  disable_services_on_destroy = false
  activate_apis               = ["apphub.googleapis.com", "cloudresourcemanager.googleapis.com"]
}
